<?php
	$checkout = Mage::getSingleton('checkout/session')->getQuote();
	$helper = Mage::helper('catalog/product_configuration');
	$items=$checkout->getAllItems();
	$prescriptions=false;
	foreach($items as $item){
		$options = $helper->getCustomOptions($item);
		foreach($options as $option){
			if($option['label']=='Prescriptions' && $option['value']!='No prescription'){
				$prescriptions=true;
			}
		}
		if($item->getProduct()->getSku()=="rowley-care"){
			$care_product=true;
		}
	}
	if(count($checkout->getAllItems())>0){
?>
<div class="cart">
    <div class="page-title">
        <h1><?php echo $this->__('Shopping Cart') ?></h1>
    </div>
    <?php echo $this->getMessagesBlock()->toHtml() ?>
    <?php echo $this->getChildHtml('form_before') ?>
    <form action="<?php echo $this->getUrl('checkout/cart/updatePost') ?>" method="post">
        <?php echo $this->getBlockHtml('formkey'); ?>
        <fieldset>
            <table id="shopping-cart-table" class="data-table cart-table">
                <col width="1" />
                <col />
                <col width="1" />
            <?php if ($this->helper('tax')->displayCartPriceExclTax() || $this->helper('tax')->displayCartBothPrices()): ?>
                <col width="1" />
            <?php endif; ?>
            <?php if ($this->helper('tax')->displayCartPriceInclTax() || $this->helper('tax')->displayCartBothPrices()): ?>
                <col width="1" />
            <?php endif; ?>
                <col width="1" />
            <?php if ($this->helper('tax')->displayCartPriceExclTax() || $this->helper('tax')->displayCartBothPrices()): ?>
                <col width="1" />
            <?php endif; ?>
            <?php if ($this->helper('tax')->displayCartPriceInclTax() || $this->helper('tax')->displayCartBothPrices()): ?>
                <col width="1" />
            <?php endif; ?>
                <col width="1" />

            <?php $mergedCells = ($this->helper('tax')->displayCartBothPrices() ? 2 : 1); ?>
                <thead>
                    <tr>
                        <th>Product</th>
                        <th>&emsp;</th>
                        <th>Price</th>
                        <th>Qty</th>
                        <th>&emsp;</th>
                    </tr>
                    <?php if ($this->helper('tax')->displayCartBothPrices()): ?>
                    <tr>
                        <th class="a-right"><?php echo $this->helper('tax')->getIncExcTaxLabel(false) ?></th>
                        <th><?php echo $this->helper('tax')->getIncExcTaxLabel(true) ?></th>
                        <th class="a-right"><?php echo $this->helper('tax')->getIncExcTaxLabel(false) ?></th>
                        <th><?php echo $this->helper('tax')->getIncExcTaxLabel(true) ?></th>
                    </tr>
                    <?php endif; ?>
                </thead>
                <tfoot>
                    <tr>
                        <td colspan="50" class="a-right">
                            
                            <button type="submit" name="update_cart_action" value="update_qty" title="<?php echo $this->__('Update Shopping Cart'); ?>" class="button btn-update"><span><span><?php echo $this->__('Update Shopping Cart'); ?></span></span></button>
                            <button type="submit" name="update_cart_action" value="empty_cart" title="<?php echo $this->__('Clear Shopping Cart'); ?>" class="button btn-empty" id="empty_cart_button"><span><span><?php echo $this->__('Clear Shopping Cart'); ?></span></span></button>
                             <div class="totals">
            						<?php echo $this->getChildHtml('totals'); ?>
            						<?php if(!$this->hasError()): ?>
            <?php
				if($prescriptions==true):
					
				?>
				<ul class="checkout-types bottom">
					<li class="method-checkout-cart-methods-onepage-bottom"> 
						<a href="<?php echo $this->getUrl('') ?>prescriptions/" style="display:block" id="pers_true" type="button" title="Proceed to Checkout" class="button btn-proceed-checkout btn-checkout">Proceed to Checkout</a>
					</li>
            	</ul>            		
            	<?php else: ?>
            		<ul class="checkout-types bottom" id="check_btn">
            			<?php foreach ($this->getMethods('methods') as $method): ?>
                			<?php if ($methodHtml = $this->getMethodHtml($method)): ?>
                				<?php if($method!="checkout.cart.methods.onepage.bottom"): ?>
                					<li class="method-<?php echo preg_replace("/[^_a-zA-Z0-9-]/", '-', $method); ?>"><?php echo $methodHtml; ?></li>
                				<?php else: ?>
                					<li class="method-checkout-cart-methods-onepage-bottom">
                						
                						<button type="button" title="Proceed to Checkout" class="button btn-proceed-checkout btn-checkout" onclick="window.location='<?php echo Mage::getBaseUrl(Mage_Core_Model_Store::URL_TYPE_WEB); ?>onestepcheckout/index/';"><span><span>Proceed to Checkout</span></span></button></li>
                				<?php endif; ?>
                			<?php endif; ?>
            			<?php endforeach; ?>
            		</ul>
            	<?php endif; ?>
            <?php endif; ?>
        					</div>
                            <!--[if lt IE 8]>
                            <input type="hidden" id="update_cart_action_container" />
                            <script type="text/javascript">
                            //<![CDATA[
                                Event.observe(window, 'load', function()
                                {
                                    // Internet Explorer (lt 8) does not support value attribute in button elements
                                    $emptyCartButton = $('empty_cart_button');
                                    $cartActionContainer = $('update_cart_action_container');
                                    if ($emptyCartButton && $cartActionContainer) {
                                        Event.observe($emptyCartButton, 'click', function()
                                        {
                                            $emptyCartButton.setAttribute('name', 'update_cart_action_temp');
                                            $cartActionContainer.setAttribute('name', 'update_cart_action');
                                            $cartActionContainer.setValue('empty_cart');
                                        });
                                    }

                                });
                            //]]>
                            </script>
                            <![endif]-->
                        </td>
                    </tr>
                </tfoot>
                <tbody>
                <?php foreach($this->getItems() as $_item): ?>
                    <?php echo $this->getItemHtml($_item) ?>
                <?php endforeach ?>
                </tbody>
            </table>
            <script type="text/javascript">decorateTable('shopping-cart-table')</script>
        </fieldset>
    </form>
    <div class="cart-collaterals">
        <div class="col2-set">
            <div class="col-1">
                <?php echo $this->getChildHtml('crosssell') ?>
            </div>
            <div class="col-2">
                <?php /* Extensions placeholder */ ?>
                <?php echo $this->getChildHtml('checkout.cart.extra') ?>
                <?php echo $this->getChildHtml('coupon') ?>
            </div>
        </div>
       
    </div>
</div>
	<?php } else{ ?>
	<div class="cart">
    <div class="page-title">
        <h1><?php echo $this->__('Shopping Cart') ?></h1>
    </div>
	<div style="min-height: 300px;padding: 20px;text-align: center;">
		You have no items in your shopping cart.
		Click <a href="<?php echo $this->getUrl('') ?>">here</a> to continue shopping.
	</div>
	</div>
<?php } ?>