<?php
  $cookie = Mage::getModel("core/cookie");
  $iphone = $cookie->get("iphone");
  $fl=Mage::getStoreConfig('makgento/header_footer/footer',Mage::app()->getStore());
  $footer_links=explode(',',$fl);
?>
<?php if($iphone != 'true'): ?>
    <div class="footer">
    	<ul class="footer_links">
    		<?php if(Mage::getSingleton('customer/session')->isLoggedIn()): ?>
    			<li><a href="<?php echo Mage::getUrl('customer/account'); ?>">My Account</a></li>
    			<li><a href="<?php echo Mage::helper('customer')->getLogoutUrl(); ?>">Log Out</a></li>
    		<?php else: ?>
    			<li><a href="<?php echo Mage::helper('customer')->getLoginUrl(); ?>">Log In/ Register</a></li>
    		<?php endif; ?>
    		<li><a href="<?php echo Mage::getUrl('contacts'); ?>">Contact Us</a></li>
    		<?php if(count($footer_links)>0): ?>
    			<?php foreach($footer_links as $f): ?>
    				<?php $pageTitle = Mage::getModel('cms/page')->load($f, 'identifier')->getTitle(); ?>
    				<li><a href="<?php echo $this->getUrl('').$f; ?>"><?php echo $pageTitle; ?></a></li>
    			<?php endforeach; ?>
    		<?php endif; ?>
    	</ul>
       <div id="copyright"><?php echo $this->getCopyright() ?></div>
    </div>
<?php endif; ?>

