<script type="text/javascript">
   function addCategory() {
       for(var i=1;i<11;i++){
   			var a='row_makgento_home_page_makgento_category_images_'+i;
   			var b='makgento_home_page_makgento_category_images_'+i;
   			if(document.getElementById(b).value=='' && document.getElementById(a).style.display=='none'){
   				document.getElementById(a).style.display='table-row';
   				break;
   			}
   		}
    }
</script>
 
<?php echo $this->getButtonHtml(); ?>
